config/routes.rb
BatchManagementSystem::Application.routes.draw do

devise_for :users, :path_names => {:sign_in => 'login', 
              :sign_out => 'logout',    
	      :password => 'secret',    
	      :confirmation => 'verification', 
	      :root_path => 'home#index'  
	      } 

  resources :trainers do
    collection do
      delete 'destroy_multiple'
    end
  end
match '/studentinfo' => 'enquiries#studentinfo', via: :get
resources :enquiries do
    collection do
      delete 'destroy_multiple'
    end
  end

    match'/grades/:grade_id/fees' => 'grades#fees', via: :get, as: :fees
    resources :sponsors do
    collection do
      delete 'destroy_multiple'
    end
  end

      match'/:grade_id/subjects/update_multiple' => 'grades#update_multiple', :via =>[:get, :put ], as: :update_multiple
  resources :grades, :shallow => true do
collection do
     delete 'multipledelete'
end
    resources :batches do
collection do
     delete 'multipledelete'
end
      resources :lectures
      resources :exams
    end
  end
 resources :subjects do
   collection do
     delete 'destroy_multiple'
   end
 end

  resources :states do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :cities do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :students do
    collection do
      delete 'destroy_multiple'
       post 'assign_batch_multiple'
    end
  end

  match'/students/:student_id/banmultiple' => 'students#banmultiple', :via => [:get, :put], as: :banmultiple
  match '/index_action' => 'students#index_action', :via => :get
  match '/grades/:grade_id/batches' => 'batches#index' 
  match'/students/:student_id/addmition' => 'students#addmition', :via => [:get, :post], as: :addmition

  match '/assign_batch' => 'students#assign_batch', :via => [:get, :post]
  match '/addgrade' => 'students#addgrade', :via => [:get, :post], as: :addgrade
  match '/student/:state_id/city' => 'students#city', :via => :get, as: :city
  match '/students/:grade_id/assign_batch_multiple' => 'students#assign_batch_multiple', :via => [:get, :post], as: :assign_batch_multiple
  match '/grade/:grade_id/subjects' => 'grades#subjects_list', :via => [:get, :post], as: :subjects_list
  match '/grade/:grade_id/batch/:batch_id/students' => 'batches#assignbatch', :via => [:get, :post], as: :assignbatch
    match '/students/:student_id/document' => 'students#document', via: :get
  match '/grades/batch/:batch_id/attendents' => 'batches#attendents', :via => [:get, :post], as: :attendents

  match'/marking_pattens/:marking_patten_id' => 'grades#destroy_marking_patten', :via => :delete, as: :destroy_marking_patten
  match '/studentinfo' => 'enquiries#studentinfo', via: :get
  match'/grade/:grade_id/subjects/update_multiple' => 'grades#update_multiple', :via =>[:get, :put ], as: :update_multiple
  match'/enquiry/:enquiry_id/students/new' => 'students#enrollement', :via => :get, as: :enrollement

match '/trainers/:trainer_id/ability' => 'trainers#ability', :via => [:get, :post], as: :ability
match 'trainers/:trainer_id/display' => 'trainers#display', :via =>  :get, as: :display
root :to => 'home#index'

end

app/models/grade.rb
class Grade < ActiveRecord::Base
   attr_accessible :title, :description, :student_fee, :sponsor_fee, :batch_duration, :session_duration
    has_many :marking_pattens
    has_many :subjects, :through => :marking_pattens
    has_many :admissions
    has_many :students, :through => :admissions
     has_many :batches, :dependent => :destroy
    validates :title, :description, :presence => true 
    validates :session_duration,:format => { :with => /^[0-2][0-3]:[0-5][0-9]$/, :message => "Not a valid time"}, :allow_blank => false

end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  def index
    @grades = Grade.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @grades }
    end
  end

  def show
    @grade = Grade.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @grade }
    end
  end

  def new
    @grade = Grade.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @grade }
    end
  end
  def edit
    @grade = Grade.find(params[:id])
  end

  def create
    @grade = Grade.new(params[:grade])

    respond_to do |format|
      if @grade.save
        format.html { redirect_to grades_path, notice: 'Grade was successfully created.' }
        format.json { render json: @grade, status: :created, location: @grade }
      else
        format.html { render action: "new" }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @grade = Grade.find(params[:id])

    respond_to do |format|
      if @grade.update_attributes(params[:grade])
        format.html { redirect_to grades_path, notice: 'Grade was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  def multipledelete
    respond_to do |format|
      if params[:grades] != nil
        Grade.destroy(params[:grades])
        format.html { redirect_to grades_url }
        format.json { head :no_content }
      else
        format.html { redirect_to grades_url }
        format.json { head :no_content }
      end
    end
  end

  def subjects_list
    @grade = Grade.find(params[:grade_id])
    @marking_pattens = @grade.marking_pattens
    if @grade.subjects.count > 0
      @subjects = Subject.where("id NOT IN (?)", @grade.subjects)
    else
      @subjects = Subject.all
    end
    if request.post?
      params[:subjects].each do |subject_id|
	@marking_patten = MarkingPatten.new()
	@marking_patten.grade_id = @grade.id
	@marking_patten.subject_id = subject_id
	@marking_patten.save
      end
      redirect_to subjects_list_path
    end
  end

  def destroy_marking_patten
    @marking_patten = MarkingPatten.find(params[:marking_patten_id])
    @marking_patten.destroy

    respond_to do |format|
      format.html { redirect_to grades_path }
      format.json { head :no_content }
    end
  end

  def update_multiple
    @grade = Grade.find(params[:grade_id])
    @marking_pattens = @grade.marking_pattens
    if request.put?
      params[:marking_patterns_ids].each do |marking_pattern_id|
	@marking_pattern = MarkingPatten.find(marking_pattern_id)
	marks = params[:marking_patterns]
        @marking_pattern.marks = marks[marking_pattern_id]
        @marking_pattern.save
      end
      flash[:notice] = "Update marking patterns."
      redirect_to subjects_list_path(@grade.id)
    end
  end

  def fees
      @grade = Grade.find(params[:grade_id])

    respond_to do |format|

format.js {@grade}
end
	end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/views/grades/_form.html.haml
= simple_form_for(@grade) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :description, :as => :text, :required => true, :input_html => {:cols => 20, :rows => 5}
    = f.input :student_fee
    = f.input :sponsor_fee
    = f.input :batch_duration
    = f.input :session_duration
  .form-actions
    = f.button :submit

app/views/grades/edit.html.haml
%h1 Editing grade

= render 'form'

= link_to 'Show', @grade
\|
= link_to '<button type="button">Cancel</button>'.html_safe, grades_path

app/views/grades/fees.html.haml
%h1 Hello!

app/views/grades/fees.js.haml
student_fees = #{@grade.student_fee};
sponsor_fees = #{@grade.sponsor_fee};
batch_duration = #{@grade.batch_duration};

app/views/grades/index.html.haml
%h1 Showing all  grades
= form_tag multipledelete_grades_path, method: :delete do
  %table.table
    %tr
      %th Select grade
      %th Title
      %th
      %th
      %th
    - @grades.each do |grade|
      %tr
        %td= check_box_tag "grades[]", grade.id
        %td= grade.title
        %td= link_to 'Show Batches', grade_batches_path(grade)
        %td= link_to 'Show Details', grade_path(grade)
        %td= link_to 'Edit', edit_grade_path(grade)
        %td= link_to "Subject and marks", subjects_list_path(grade)
  = submit_tag "Delete selected grades"
  = link_to '<button type="button">New Grade</button>'.html_safe, new_grade_path

app/views/grades/new.html.haml
%h1 New grade

= render 'form'

= link_to '<button type="button">Cancel</button>'.html_safe, grades_path

app/views/grades/show.html.haml
%h1 Grade Details
%table
  %tr
    %th Title
    %th Description
    %th Student_Fee
    %th Sponsors_fee
    %th Batch_duration
    %th Session_duration

    %th
      %tr
        %td= @grade.title
        %td= @grade.description
        %td= @grade.student_fee
        %td= @grade.sponsor_fee
        %td= @grade.batch_duration
        %td= @grade.session_duration
%br
= link_to '<button type="button">Back</button>'.html_safe, grades_path
%br

app/views/grades/subjects_list.html.haml
%h1 Subjects taught in #{@grade.title}
%h2 Marking pattern
%table.table
  %tr
    %th Subject name
    %th Mark
  
  - @marking_pattens.each do |marking_patten|
    %tr
      %td= marking_patten.subject.subject
      %td= marking_patten.marks
      %td= link_to "Remove", destroy_marking_patten_path(marking_patten), :method => :delete, :data => { :confirm => 'Are you sure?' }
- if @marking_pattens.size > 0
  = link_to  '<button type="button">Update marking pattern</button>'.html_safe, update_multiple_path(@grade.id)

- if @subjects.size > 0 
  %h2 Introduce new subjects
  = simple_form_for subjects_list_path, method: :post do |f|
    %table.table
      %tr
        %th Select subjects
        %th Subject name

      - @subjects.each do |subject|
        %tr
          %td= check_box_tag "subjects[]", subject.id
          %td= subject.subject


    = submit_tag "Assign subjects"
 

app/views/grades/update_multiple.html.haml
%h2 Marking pattern
= simple_form_for @marking_pattens, url: update_multiple_path, method: :put do |f|
  %table.table
    %tr
      %th
      %th Subject name
      %th#marks Mark
      %th Action
  
    - @marking_pattens.each do |marking_patten|
      %tr
        %td= hidden_field_tag "marking_patterns_ids[]", marking_patten.id
        %th{:id => "s_#{marking_patten.id}"}= marking_patten.subject.subject
        %td{:headers => "s_#{marking_patten.id} marks"}= text_field_tag "marking_patterns[#{marking_patten.id}]", "#{marking_patten.marks}"
        %td= link_to "Remove", destroy_marking_patten_path(marking_patten), :method => :delete, :data => { :confirm => 'Are you sure?' }
  = submit_tag "Update marking pattern"    
  = link_to '<button type="button">Cancel</button>'.html_safe, subjects_list_path(@grade.id) 