config/routes.rb
BatchManagementSystem::Application.routes.draw do

devise_for :users, :path_names => {:sign_in => 'login', 
              :sign_out => 'logout',    
	      :password => 'secret',    
	      :confirmation => 'verification', 
	      :root_path => 'home#index'  
	      } 

  resources :trainers do
    collection do
      delete 'destroy_multiple'
    end
  end
match '/studentinfo' => 'enquiries#studentinfo', via: :get
resources :enquiries do
    collection do
      delete 'destroy_multiple'
    end
  end

    match'/grades/:grade_id/fees' => 'grades#fees', via: :get, as: :fees
    resources :sponsors do
    collection do
      delete 'destroy_multiple'
    end
  end

      match'/:grade_id/subjects/update_multiple' => 'grades#update_multiple', :via =>[:get, :put ], as: :update_multiple
  resources :grades, :shallow => true do
collection do
     delete 'multipledelete'
end
    resources :batches do
collection do
     delete 'multipledelete'
end
      resources :lectures
      resources :exams
    end
  end
 resources :subjects do
   collection do
     delete 'destroy_multiple'
   end
 end

  resources :states do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :cities do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :students do
    collection do
      delete 'destroy_multiple'
       post 'assign_batch_multiple'
    end
  end

  match'/students/:student_id/banmultiple' => 'students#banmultiple', :via => [:get, :put], as: :banmultiple
  match '/index_action' => 'students#index_action', :via => :get
  match '/grades/:grade_id/batches' => 'batches#index' 
  match'/students/:student_id/addmition' => 'students#addmition', :via => [:get, :post], as: :addmition

  match '/assign_batch' => 'students#assign_batch', :via => [:get, :post]
  match '/addgrade' => 'students#addgrade', :via => [:get, :post], as: :addgrade
  match '/student/:state_id/city' => 'students#city', :via => :get, as: :city
  match '/students/:grade_id/assign_batch_multiple' => 'students#assign_batch_multiple', :via => [:get, :post], as: :assign_batch_multiple
  match '/grade/:grade_id/subjects' => 'grades#subjects_list', :via => [:get, :post], as: :subjects_list
  match '/grade/:grade_id/batch/:batch_id/students' => 'batches#assignbatch', :via => [:get, :post], as: :assignbatch
    match '/students/:student_id/document' => 'students#document', via: :get
  match '/grades/batch/:batch_id/attendents' => 'batches#attendents', :via => [:get, :post], as: :attendents

  match'/marking_pattens/:marking_patten_id' => 'grades#destroy_marking_patten', :via => :delete, as: :destroy_marking_patten
  match '/studentinfo' => 'enquiries#studentinfo', via: :get
  match'/grade/:grade_id/subjects/update_multiple' => 'grades#update_multiple', :via =>[:get, :put ], as: :update_multiple
  match'/enquiry/:enquiry_id/students/new' => 'students#enrollement', :via => :get, as: :enrollement

match '/trainers/:trainer_id/ability' => 'trainers#ability', :via => [:get, :post], as: :ability
match 'trainers/:trainer_id/display' => 'trainers#display', :via =>  :get, as: :display
root :to => 'home#index'

end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :country
  belongs_to :state
  belongs_to :city
  has_many :presenties
  has_many :lectures, :through => :presenties
  has_many :results
  has_many :exams, :through => :results
  has_many :admissions
  has_many :grades, :through => :admissions
  has_and_belongs_to_many :batches
  attr_accessible :address_line1, :address_line2, :alternate_mobile, :email, :enrollment_date, :first_name, :last_name, :middle_name, :mobile, :qualifies_with, :sponsor, :zip_code, :state_id, :city_id, :country_id, :photo, :ban, :date_of_birth, :address_proof, :blindness_certificate, :address, :blindness
  has_attached_file :photo  
  has_attached_file :address  
  has_attached_file :blindness  


  
  attr_accessible :address_line1, :address_line2, :alternate_mobile, :email, :enrollment_date, :first_name, :last_name, :middle_name, :mobile, :zip_code, :state_id, :city_id, :country_id, :photo, :ban, :date_of_birth, :address_proof, :blindness_certificate
  has_attached_file :photo  

  validates :first_name, :last_name, :address_line1, :mobile, :enrollment_date, :zip_code,	:state_id, :city_id, :presence => true
  #validates :first_name,  :last_name, :format => {:with => /\A[a-zA-z]+\z/, :message => "Only letters allowed."}
  validates :middle_name, :format => {:with => /\A[a-zA-z]+\z/, :message => "Only letters allowed."}, :allow_blank => true
  validates :email, :format => { :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i , :message => "Not a valid email address"}, :allow_blank => true
  validates :zip_code, :format => { :with => /^\d{6}$/, :message => "Please provide 6 digit pin code" }
  validates :mobile, :alternate_mobile, :format => { with: /(^\s*$|^\s*[789]\d{9}\s*$)/, :message => "Please provide 10 digit mobile number." }
  validates_attachment :photo, :presence => true, :content_type => { :content_type => ['image/jpg', 'image/png', 'image/jpeg']}
  validates_attachment :blindness, :presence => true, :content_type => { :content_type => ['image/jpg', 'image/png', 'image/jpeg']}
  #valid_presence_of :blindness, :message => "Please upload your blindness  "
validates_attachment_presence :blindness, :message => 'xxxx'

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
#    @student.grades.build
  end

  def enrollement
    @enquiry = Enquiry.find(params[:enquiry_id])
    @student = Student.new
  end

  def edit
    @student = Student.find(params[:id])
  end

  def create
    @student = Student.new(params[:student])
    #@enquiry = Enquiry.find(params[:enquiry_id])

    p "----------------"
    #@enquiry.destroy

    p params
    respond_to do |format|
      if @student.save
p "The an Inquery is"
#p @inquiry

        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @student = Student.find(params[:id])
    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy_multiple
	 respond_to do |format|
 if params[:students] !=nil
	 Student.destroy(params[:students])
      format.html { redirect_to students_url }
        format.json { head :no_content }
      else
        format.html { redirect_to students_url }
        format.json { head :no_content }
      end
    end
   end

  def city
    @state = State.find(params[:state_id])    
    @cities = @state.cities
    render :update do |page|
      page.replace_html "cities", :partial => "city", :object => @cities
    end
  end

  def state
    @country = Country.find(params[:country_id])
    @states = @country.states
  end

#def addgrade  
  #if request.post?
    #@student = Admission .new(params[:admission ])
    #@student.admission_date = Date.today
    #respond_to do |format|
      #if @student.save
        #format.html { redirect_to students_path, notice: 'assign grade successfully..' }
 #       format.json { render json: students_path, status: :created, location: @student }
  #    else
   #     format.html { render action: "addgrade" }
     #   format.json { render json: @student.errors, status: :unprocessable_entity }
     # end
   # end
  #end
# end


  def banmultiple
    p params
    p "--------------"
    p @student
    if request.put?
    @student = Student.find(params[:student_id])

      respond_to do |format|
        @student.ban = true    
        @student.update_attributes(params[:student])
        format.html { redirect_to students_path, notice: @student.first_name + " " + @student.last_name + " has been ban. "}	
      end
    end
  end


  def assign_batch_multiple    
    @grade = Grade.find(params[:grade_id])
    @students = @grade.students
     if request.post?
      @students = BatchesStudents.new(params[:batches_students])
      respond_to do |format|
        if @student.save
          format.html { redirect_to students_path, notice: 'assign batch successfully..' }
          format.json { render json: students_path, status: :created, location: @student }
        else
          format.html { render action: "assign_batch" }
          format.json { render json: @student.errors, status: :unprocessable_entity }
        end
      end
    end
  end

	  def addmition
    @student =  Student.find(params[:student_id])
    @admission = Admission.new

  if request.post?
    @addmition = Admission.new(params[:admission])
    @addmition.student_id = @student.id
p "the params is,"
p params

    #@addmition.student_id = params[:student_id]
   # @addmition.admission_date = params[:admission_date]
    #@addmition.student_fee = params[:student_fee]

    #@addmition.sponsor_id = params[:sponsor_id]
    #@addmition.grade_id = params[:grade_id]
    #@addmition.sponsor_fee = params[:sponsor_fee]
  if @addmition.save

    redirect_to students_path
  else
# do nothing
    end
end
  end
    def document
        @student = Student.find(params[:student_id])
	  end
	  end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_addmition.html.haml
= simple_form_for @admission, :url => addmition_path(@student), method: :post do |f|
  = f.input :admission_date, :as => :datepicker, :readonly => true
  = f.input :grade_id, :collection => Grade.all.entries, :value_method => :id, :label_method =>  :title, :input_html => {:id => "comgrade"}
  = f.input :student_fee, :label => "Student has paid Rs.", :readonly => true, :input_html => {:id => "text_student_fees"}
  = f.input :sponsor_flag, as: :boolean, :label => "Student needs sponsorship", :input_html => {:id => "sponsor_required"}
  #sponsorship_details{:style => "display:none;"}
    = f.input :sponsor_id, :collection => Sponsor.all.entries, :value_method => :id, :label_method =>  :first_name
    = f.input :sponsor_fee, :label => "Sponsor has paid Rs.", :readonly => true, :input_html => {:id => "text_sponsor_fees"}
  = f.hidden_field :student_id
  = f.submit"submit"

app/views/students/_assign_batch_multiple.html.haml
= simple_form_for assign_batch_multiple_path, method: :post do |f|
  = f.input :batch_id, :collection => @grade.batches.all.entries, :label_method => :title, :value_method => :id, :prompt => "Select batch"
  %h2 Student list for assign grade
  = render "students_list" 
  
  = submit_tag "Assign batch"

app/views/students/_form.html.haml
= simple_form_for @student, :html => { :multipart => true} do |f|
  = f.error_notification

  .form-inputs
    = f.input :first_name
    = f.input :middle_name
    = f.input :last_name 
    = f.input :date_of_birth, :as => :datepicker, :readonly => true     
    = f.input :email
    = f.input :mobile
    = f.input :alternate_mobile
    = f.input :address_line1
    = f.input :address_line2
    = f.association :country, :collection => Country.all.entries, :prompt => "Select country" 
    = f.association :state, :collection => State.all.entries, :prompt => "Select state" 
    = f.association :city, :collection => City.all.entries, :prompt => "Select city" 
    = f.input :zip_code
    = f.input :enrollment_date, :as => :datepicker, :readonly => true
    = f.label :photo
    = f.file_field :photo
    = f.label :address
    = f.file_field :address
    = f.label :blindness
    = f.file_field :blindness

  .form-actions
    = f.button :submit



  

app/views/students/_students_list.html.haml
%table.table
  %tr
    %th Select students
    %th Full name
    %th

  - @students.each do |student|
    %tr
      %td= check_box_tag "students[]", student.id
      %td= student.first_name + " " + student.last_name
      %td= link_to "Show Details", student_path(student)
      %td= link_to "Fill admission form", addmition_path(student)
      %td= link_to 'Edit', edit_student_path(student)
      %td= link_to "Ban this student", banmultiple_path(student), method: :put

app/views/students/addgrade.html.haml
%h1 Assign grade
= simple_form_for Admission .new, :url => addgrade_path, method: :post do |f|

  = f.error_notification
  = f.input :student_id, :collection => Student.all.entries, :label_method => :first_name, :value_method => :id, :prompt => "Select student"
  = f.input :grade_id, :collection => Grade.all.entries, :label_method => :title, :value_method => :id, :prompt => "Select grade"


  = f.submit
%br
= link_to '<button type ="button">Cancel</button>'.html_safe, students_path

app/views/students/addmition.html.haml
%h1 Student Addmition
= render 'addmition'

app/views/students/assign_batch.html.haml
%h1 Assign batch
%td= select_tag 'grade', options_from_collection_for_select(Grade.all.entries, :id, :title), :id => "combgrade", :prompt => "Select grade"
%div{ :id => "studentListForm"}

%br
= link_to '<button type ="button">Cancel</button>'.html_safe, students_path

app/views/students/assign_batch_multiple.js.haml
$('#studentListForm').html('#{escape_javascript(render :partial => 'assign_batch_multiple')}')

app/views/students/document.html.haml
%h1 documents

app/views/students/edit.html.haml
%h1 Editing student
= render 'form'

= link_to '<button type ="button">Show</button>'.html_safe, @student
\|
= link_to '<button type ="button">Cancel</button>'.html_safe, students_path

app/views/students/enrollement.html.haml
%h1 New student
= simple_form_for @student, :html => { :multipart => true} do |f|
  = f.error_notification

  .form-inputs
    = hidden_field :enquiry_id, :value => @enquiry.id
    = f.input :first_name, :input_html => {:value => "#{@enquiry.first_name}" }
    = f.input :middle_name, :input_html => {:value => "#{@enquiry.middle_name}" }
    = f.input :last_name, :input_html => {:value => "#{@enquiry.last_name}" } 
    = f.input :date_of_birth, :as => :datepicker, :readonly => true     
    = f.input :email
    = f.input :mobile, :input_html => {:value => "#{@enquiry.mobile}" }
    = f.input :alternate_mobile
    = f.input :address_line1, :input_html => {:value => "#{@enquiry.address_line1}" }
    = f.input :address_line2, :input_html => {:value => "#{@enquiry.address_line2}" }
    = f.association :country, :collection => Country.all.entries, :prompt => "Select country", :selected => [Country.first.id]
    = f.association :state, :collection => State.all.entries, :prompt => "Select state", :selected => [@enquiry.state.id]
    = f.association :city, :collection => City.all.entries, :prompt => "Select city", :selected => [@enquiry.city.id]
    = f.input :zip_code, :input_html => {:value => "#{@enquiry.zip_code}" }
    = f.input :enrollment_date, :as => :datepicker, :readonly => true
    = f.input :address_proof, :as => :boolean
    = f.input :blindness_certificate, :as => :boolean    
    = f.file_field :photo

  .form-actions
    = f.button :submit



  

app/views/students/index.html.haml
%h1 Students list
= form_tag destroy_multiple_students_path, method: :delete  do 
  = render "students_list"
  = submit_tag "delete selected"
  = link_to '<button type ="button">New Student</button>'.html_safe, new_student_path
 

app/views/students/new.html.haml
%h1 New student

= render 'form'

= link_to '<button type="button">Cancel</button>'.html_safe, students_path

app/views/students/show.html.haml
%h1 Student details
%br
= image_tag @student.photo.url, :alt => @student.first_name, html: {:width => 100, :height => 100}
%br
- if @student.address == nil?
  = image_tag @student.address.url, :alt => @student.address, html: {:width => 100, :height => 100}
- else
  %b You haven't uploaded your address related documents
%br
- if @student.blindness == nil?
  = image_tag @student.blindness.url, :alt => @student.blindness, html: {:width => 100, :height => 100}
- else
  %b You haven't uploaded your blindness

%br
%h2 Personal information
%table
  %tr
    %th Full name
    %th Middle name
    %th Mobile number
    %th Date Of Birth
    - if @student.alternate_mobile != nil && @student.alternate_mobile != ""
      %th Alternate mobile
    %th Email
  %tr
    %td= @student.first_name  +  " "  +  @student.last_name
    %td= @student.middle_name
    %td= @student.mobile
    %td= @student.date_of_birth
    - if @student.alternate_mobile != nil && @student.alternate_mobile != ""
      %td= @student.alternate_mobile
    %td= @student.email

%h2 Address information
%table
  %tr
    %th Address line1
    %th Address line2
    %th Location
    %th Country
    %th Pin code
    %th Address Proof
  %tr
    %td= @student.address_line1
    %td= @student.address_line2
    %td= @student.city.name + " " + @student.state.name
    %td= @student.country.name
    %td= @student.zip_code
    %td= @student.address_proof

%h2 Other information
%table
  %tr
    %th Enrollment date
    %th Blindness Certificate
  %tr
    %td= @student.enrollment_date
    %td= @student.blindness_certificate
%br
= link_to '<button type="button">Back</button>'.html_safe, students_path