config/routes.rb
BatchManagementSystem::Application.routes.draw do

devise_for :users, :path_names => {:sign_in => 'login', 
              :sign_out => 'logout',    
	      :password => 'secret',    
	      :confirmation => 'verification', 
	      :root_path => 'home#index'  
	      } 

  resources :trainers do
    collection do
      delete 'destroy_multiple'
    end
  end
match '/studentinfo' => 'enquiries#studentinfo', via: :get
resources :enquiries do
    collection do
      delete 'destroy_multiple'
    end
  end

    match'/grades/:grade_id/fees' => 'grades#fees', via: :get, as: :fees
    resources :sponsors do
    collection do
      delete 'destroy_multiple'
    end
  end

      match'/:grade_id/subjects/update_multiple' => 'grades#update_multiple', :via =>[:get, :put ], as: :update_multiple
  resources :grades, :shallow => true do
collection do
     delete 'multipledelete'
end
    resources :batches do
collection do
     delete 'multipledelete'
end
      resources :lectures
      resources :exams
    end
  end
 resources :subjects do
   collection do
     delete 'destroy_multiple'
   end
 end

  resources :states do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :cities do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :students do
    collection do
      delete 'destroy_multiple'
       post 'assign_batch_multiple'
    end
  end

  match'/students/:student_id/banmultiple' => 'students#banmultiple', :via => [:get, :put], as: :banmultiple
  match '/index_action' => 'students#index_action', :via => :get
  match '/grades/:grade_id/batches' => 'batches#index' 
  match'/students/:student_id/addmition' => 'students#addmition', :via => [:get, :post], as: :addmition

  match '/assign_batch' => 'students#assign_batch', :via => [:get, :post]
  match '/addgrade' => 'students#addgrade', :via => [:get, :post], as: :addgrade
  match '/student/:state_id/city' => 'students#city', :via => :get, as: :city
  match '/students/:grade_id/assign_batch_multiple' => 'students#assign_batch_multiple', :via => [:get, :post], as: :assign_batch_multiple
  match '/grade/:grade_id/subjects' => 'grades#subjects_list', :via => [:get, :post], as: :subjects_list
  match '/grade/:grade_id/batch/:batch_id/students' => 'batches#assignbatch', :via => [:get, :post], as: :assignbatch
    match '/students/:student_id/document' => 'students#document', via: :get
  match '/grades/batch/:batch_id/attendents' => 'batches#attendents', :via => [:get, :post], as: :attendents

  match'/marking_pattens/:marking_patten_id' => 'grades#destroy_marking_patten', :via => :delete, as: :destroy_marking_patten
  match '/studentinfo' => 'enquiries#studentinfo', via: :get
  match'/grade/:grade_id/subjects/update_multiple' => 'grades#update_multiple', :via =>[:get, :put ], as: :update_multiple
  match'/enquiry/:enquiry_id/students/new' => 'students#enrollement', :via => :get, as: :enrollement

match '/trainers/:trainer_id/ability' => 'trainers#ability', :via => [:get, :post], as: :ability
match 'trainers/:trainer_id/display' => 'trainers#display', :via =>  :get, as: :display
root :to => 'home#index'

end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  belongs_to :country
  belongs_to :state
  belongs_to :city
  has_many :admissions
  attr_accessible :address_line1, :address_line2, :alternate_mobile, :email, :first_name, :last_name, :middle_name, :mobile_number, :pan_number, :pin_code, :country_id, :state_id, :city_id

  #validation
  validates :first_name, :last_name, :address_line1, :mobile_number,   :pin_code,	:state_id, :city_id, :email, :pan_number, :presence => true
  validates :first_name,  :last_name, :format => {:with => /\A[a-zA-z]+\z/, :message => "Only letters allowed."}
  validates :middle_name, :format => {:with => /\A[a-zA-z]+\z/, :message => "Only letters allowed."}, :allow_blank => true
  validates :email, :format => { :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i , :message => "Not a valid email address"}
  validates :pin_code, :format => { :with => /^\d{6}$/, :message => "Plesse provide 6 digit pin code" }
  validates :mobile_number, :alternate_mobile, :format => { with: /(^\s*$|^\s*[789]\d{9}\s*$)/, :message => "Please provide 10 digit mobile number." }
  validates :pan_number, :length => { :is => 10 }, :allow_blank => true 
  validates :pan_number, :format => { :with => /\A[A-Z]{5}\d{4}[A-Z]{1}\Z/ , :message => 'invalid pan number'}, :allow_blank => true 
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  def index
    @sponsors = Sponsor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sponsors  }
    end
  end

  def show
    @sponsor  = Sponsor .find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sponsor }
    end
  end

  def new
    @sponsor = Sponsor .new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sponsor }
    end
  end

  def edit
    @sponsor  = Sponsor.find(params[:id])
  end

  def create
    @sponsor  = Sponsor .new(params[:sponsor ])

    respond_to do |format|
      if @sponsor .save
        format.html { redirect_to sponsors_path, notice: 'sponsor was successfully created.' }
        format.json { render json: @sponsor , status: :created, location: @sponsor  }
      else
        format.html { render action: "new" }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @sponsor = Sponsor .find(params[:id])

    respond_to do |format|
      if @sponsor .update_attributes(params[:sponsor ])
        format.html { redirect_to sponsors_path, notice: 'sponsor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

     def destroy_multiple
	 respond_to do |format|
 if params[:sponsors] !=nil
	 Sponsor.destroy(params[:sponsors])
      format.html { redirect_to sponsors_url }
        format.json { head :no_content }
      else
        format.html { redirect_to sponsors_url }
        format.json { head :no_content }
      end
    end
   end
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/sponsors/_form.html.haml
= simple_form_for(@sponsor) do |f|
  = f.error_notification

  .form-inputs
    = f.input :first_name
    = f.input :middle_name
    = f.input :last_name
    = f.input :email
    = f.input :mobile_number
    = f.input :alternate_mobile
    = f.input :pan_number
    = f.input :address_line1
    = f.input :address_line2
    = f.association :country, :collection => Country.all.entries, :prompt => "Select country" 
    = f.association :state, :collection => State.all.entries, :prompt => "Select state" 
    = f.association :city, :collection => City.all.entries, :prompt => "Select city" 
    = f.input :pin_code
    
  .form-actions
    = f.button :submit
 

app/views/sponsors/edit.html.haml
%h1 Editing sponsor

= render 'form'

= link_to 'Show', @sponsor
\|
= link_to '<button type="button">Cancel</button>'.html_safe, sponsors_path

app/views/sponsors/index.html.haml
%h1 Showing all  sponsors
= form_tag destroy_multiple_sponsors_path, method: :delete do
  %table.table
    %tr
      %th Select sponsor
      %th Full name
      %th Email
      %th Mobile number
      %th pan_number
      %th 
      %th
      
    - @sponsors.each do |sponsor|
      %tr
        %td= check_box_tag "sponsors[]", sponsor.id
        %td= sponsor.first_name + " " + sponsor.last_name
        %td= sponsor.email
        %td= sponsor.mobile_number
        %td= sponsor.pan_number  
        %td= link_to 'Show Details', sponsor_path(sponsor)
        %td= link_to 'Edit', edit_sponsor_path(sponsor)
  = submit_tag "Delete selected sponsors"
  = link_to '<button type="button">New Sponsor</button>'.html_safe, new_sponsor_path

app/views/sponsors/new.html.haml
%h1 New sponsor

= render 'form'

= link_to '<button type="button">Cancel</button>'.html_safe, sponsors_path

app/views/sponsors/show.html.haml
%h1 Sponsor Details
%h2 Personal information
%table.table
  %tr
    %th Full name
    %th Email
    %th Mobile number
    - if @sponsor.alternate_mobile != nil && @sponsor.alternate_mobile != ""
      %th Alternate mobile
    %th Pan number
  %tr
    %td= @sponsor.first_name + " " + @sponsor.last_name
    %td= @sponsor.email
    %td= @sponsor.mobile_number
    - if @sponsor.alternate_mobile != nil && @sponsor.alternate_mobile != ""
      %td= @sponsor.alternate_mobile
    %td= @sponsor.pan_number

%h2 Address information
%table.table
  %tr
    %th Address
  %tr
    %td= @sponsor.address_line1 + " " + @sponsor.address_line2 + " "  + @sponsor.city.name + " " + @sponsor.state.name + " " + @sponsor.pin_code.to_s

%br
= link_to '<button type ="button">Back</button>'.html_safe, sponsors_path