config/routes.rb
BatchManagementSystem::Application.routes.draw do

devise_for :users, :path_names => {:sign_in => 'login', 
              :sign_out => 'logout',    
	      :password => 'secret',    
	      :confirmation => 'verification', 
	      :root_path => 'home#index'  
	      } 

  resources :trainers do
    collection do
      delete 'destroy_multiple'
    end
  end
match '/studentinfo' => 'enquiries#studentinfo', via: :get
resources :enquiries do
    collection do
      delete 'destroy_multiple'
    end
  end

    match'/grades/:grade_id/fees' => 'grades#fees', via: :get, as: :fees
    resources :sponsors do
    collection do
      delete 'destroy_multiple'
    end
  end

      match'/:grade_id/subjects/update_multiple' => 'grades#update_multiple', :via =>[:get, :put ], as: :update_multiple
  resources :grades, :shallow => true do
collection do
     delete 'multipledelete'
end
    resources :batches do
collection do
     delete 'multipledelete'
end
      resources :lectures
      resources :exams
    end
  end
 resources :subjects do
   collection do
     delete 'destroy_multiple'
   end
 end

  resources :states do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :cities do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :students do
    collection do
      delete 'destroy_multiple'
       post 'assign_batch_multiple'
    end
  end

  match'/students/:student_id/banmultiple' => 'students#banmultiple', :via => [:get, :put], as: :banmultiple
  match '/index_action' => 'students#index_action', :via => :get
  match '/grades/:grade_id/batches' => 'batches#index' 
  match'/students/:student_id/addmition' => 'students#addmition', :via => [:get, :post], as: :addmition

  match '/assign_batch' => 'students#assign_batch', :via => [:get, :post]
  match '/addgrade' => 'students#addgrade', :via => [:get, :post], as: :addgrade
  match '/student/:state_id/city' => 'students#city', :via => :get, as: :city
  match '/students/:grade_id/assign_batch_multiple' => 'students#assign_batch_multiple', :via => [:get, :post], as: :assign_batch_multiple
  match '/grade/:grade_id/subjects' => 'grades#subjects_list', :via => [:get, :post], as: :subjects_list
  match '/grade/:grade_id/batch/:batch_id/students' => 'batches#assignbatch', :via => [:get, :post], as: :assignbatch
    match '/students/:student_id/document' => 'students#document', via: :get
  match '/grades/batch/:batch_id/attendents' => 'batches#attendents', :via => [:get, :post], as: :attendents

  match'/marking_pattens/:marking_patten_id' => 'grades#destroy_marking_patten', :via => :delete, as: :destroy_marking_patten
  match '/studentinfo' => 'enquiries#studentinfo', via: :get
  match'/grade/:grade_id/subjects/update_multiple' => 'grades#update_multiple', :via =>[:get, :put ], as: :update_multiple
  match'/enquiry/:enquiry_id/students/new' => 'students#enrollement', :via => :get, as: :enrollement

match '/trainers/:trainer_id/ability' => 'trainers#ability', :via => [:get, :post], as: :ability
match 'trainers/:trainer_id/display' => 'trainers#display', :via =>  :get, as: :display
root :to => 'home#index'

end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
  belongs_to :country
  belongs_to :state
  belongs_to :city
  
  has_and_belongs_to_many :marking_pattens
  attr_accessible :address_line1, :address_line2, :address_proof, :email, :first_name, :last_name, :middle_name, :mobile_number, :qualification, :zip_code, :country_id, :state_id, :city_id, :photo, :date_of_birth
  has_attached_file :photo  
has_attached_file :qualification  
has_attached_file :address_proof  


  validates :first_name, :last_name, :address_line1, :mobile_number, :zip_code, :state_id, :city_id, :email, :presence => true
  validates :first_name,  :last_name, :format => {:with => /\A[a-zA-z]+\z/, :message => "Only letters allowed."}
  validates :middle_name, :format => {:with => /\A[a-zA-z]+\z/, :message => "Only letters allowed."}, :allow_blank => true
  validates :email, :format => { :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i , :message => "Not a valid email address"}
  validates :zip_code, :format => { :with => /^\d{6}$/, :message => "Plesse provide 6 digit pin code" }
  validates :mobile_number, :format => { with: /(^\s*$|^\s*[789]\d{9}\s*$)/, :message => "Please provide 10 digit mobile number." }
  validates_attachment :photo, :presence => true, :content_type => { :content_type => ['image/jpg', 'image/png', 'image/jpeg']}
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController

  def index
 @trainers = Trainer.where(:delete_flag => false)

   
    end

  def show
    @trainer = Trainer.find(params[:id])
  end

  def new
    @trainer = Trainer.new
  end

  def edit
    @trainer = Trainer.find(params[:id])
  end

  def create
    @trainer = Trainer.new(params[:trainer])
    @trainer.delete_flag = false
    respond_to do |format|
      if @trainer.save
        format.html { redirect_to @trainer, notice: 'Trainer was successfully created.' }
        format.json { render json: @trainer, status: :created, location: @trainer }
      else
        format.html { render action: "new" }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

   def update
    @trainer = Trainer.find(params[:id])
    respond_to do |format|
      if @trainer.update_attributes(params[:trainer])
        format.html { redirect_to @trainer, notice: 'Trainer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy_multiple
    if params[:trainers] != nil
     Trainer.destroy(params[:trainers])
      redirect_to trainers_path
    end  
  end


def ability
   @marking_pattens = MarkingPatten.all  
if request.post?
params[:grade].each do |g|
@var =  MarkingPattensTrainers.new()
@var.trainer_id = params[:trainer_id]
@var.marking_patten_id = g
p "params is,"
p params
p "the var is,"
p @var
if @var.save

end
end
redirect_to trainers_path

  end

end

def display
@trainer = Trainer.find(params[:trainer_id])
end
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/trainers/_form.html.haml
= simple_form_for @trainer, :html => { :multipart => true} do |f|
  = f.error_notification

  .form-inputs
    = f.input :first_name
    = f.input :middle_name
    = f.input :last_name 
    = f.input :email
    = f.input :mobile_number
    = f.input :date_of_birth, :as => :datepicker, :readonly => true
    = f.input :address_line1
    = f.input :address_line2
    = f.association :country, :collection => Country.all.entries, :prompt => "Select country" 
    = f.association :state, :collection => State.all.entries, :prompt => "Select state" 
    = f.association :city, :collection => City.all.entries, :prompt => "Select city" 
    = f.input :zip_code
   
    = f.label:photo
    = f.file_field :photo
    = f.label :address_proof
    = f.file_field :address_proof
    = f.label :qualification
    = f.file_field :qualification

  .form-actions
    = f.button :submit

app/views/trainers/ability.html.haml
%h2 Ability Of Trainers
%h3 Trainers Grades and their Subjects
= simple_form_for ability_path, method: :post do |f|
  = f.hidden_field :trainer_id
  %table.table
    %tr
      %th Grade Title
      %th Subjects
    - @marking_pattens.each do |marking_patten|
      %tr
        %td= marking_patten.grade.title
        - marking_patten.grade.marking_pattens.each do |grade|
          = check_box_tag "grade[]", grade.id
          %td= grade.subject.subject
  = submit_tag "create"	

app/views/trainers/display.html.haml
%h1 Showing trainers grades and there subjects
%table.table
  %tr
    %th Trainers Grade
    %th Subject
  - @trainer.marking_pattens.each do |trainer|
    %tr
      %td= trainer.grade.title
      %td= trainer.subject.subject

app/views/trainers/edit.html.haml
%h1 Editing trainer

= render 'form'

= link_to 'Show', @trainer
\|
= link_to 'Back', trainers_path

app/views/trainers/index.html.haml
%h1 Trainers list

= form_tag destroy_multiple_trainers_path, method: :delete do
  %table.table
    %tr
      %th Select trainer
      %th Full name
      %th
      %th

    - @trainers.each do |trainer|
      %tr
        %td= check_box_tag "trainers[]", trainer.id
        %td= trainer.first_name + " " + trainer.last_name
        %td= link_to 'Show', trainer
        %td= link_to 'Edit', edit_trainer_path(trainer)
        %td= link_to 'Ability', ability_path(trainer)
        %td= link_to "Show Ability of trainer", display_path(trainer)
  = submit_tag "Delete selected"
  = link_to '<button type ="button">New Trainer</button>'.html_safe, new_trainer_path
    
    

app/views/trainers/new.html.haml
%h1 New trainer

= render 'form'

= link_to 'Back', trainers_path

app/views/trainers/show.html.haml
%p#notice= notice
%h1 Trainers details
%br
= image_tag @trainer.photo.url, :alt => @trainer.first_name, html: {:width => 100, :height => 100}
%br
= image_tag @trainer.address_proof.url, :alt => @trainer.address_proof, html: {:width => 100, :height => 100}

%br
= image_tag @trainer.qualification.url, :alt => @trainer.qualification, html: {:width => 100, :height => 100}
%br
%h2 Personal information
%table.table
  %tr
    %th Full name
    %th Mobile number
    %th Date Of Birth
    %th Email    
  %tr
    %td= @trainer.first_name  +  " "  +  @trainer.last_name
    %td= @trainer.mobile_number
    %td= @trainer.date_of_birth
    %td= @trainer.email

%h2 Address information
%table.table
  %tr
    %th Address line1
    %th Address line2
    %th Location
    %th Country
    %th Pin code
  %tr
    %td= @trainer.address_line1
    %td= @trainer.address_line2
    %td= @trainer.city.name + " " + @trainer.state.name
    %td= @trainer.country.name
    %td= @trainer.zip_code

%br
= link_to '<button type ="button">Back</button>'.html_safe, trainers_path